
PARALLEL ?= $(shell nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 1)

ifeq ($(filter -j%,$(MAKEFLAGS)),)
MAKEFLAGS += -j$(PARALLEL)
endif

TEX_SOURCES := $(sort $(wildcard tex/series/*/*.tex))

PDFS := $(TEX_SOURCES:tex/series/%.tex=build/series/%.pdf)
SOLUTIONS := $(TEX_SOURCES:tex/series/%.tex=build/series/%-solution.pdf)

LATEXMK_FLAGS := -lualatex -interaction=nonstopmode -halt-on-error -shell-escape
LATEXMK_PRETEX := \PassOptionsToClass{answers}{exam}\AtBeginDocument{\printanswers}

.PHONY: all build clean

all: clean build

build: $(PDFS) $(SOLUTIONS)

build/series/%.pdf: tex/series/%.tex revision.tex heiglogo.sty
	@mkdir -p $(@D)
	(cd $(@D) && TEXINPUTS=$(CURDIR)/tex//:$(CURDIR): latexmk $(LATEXMK_FLAGS) -output-directory=. \
        $(CURDIR)/$<)

build/series/%-solution.pdf: tex/series/%.tex revision.tex heiglogo.sty
	@mkdir -p $(@D)
	(cd $(@D) && TEXINPUTS=$(CURDIR)/tex//:$(CURDIR): latexmk $(LATEXMK_FLAGS) \
        -output-directory=. \
        -jobname=$(notdir $(basename $(@:.pdf=))) \
        -usepretex='$(LATEXMK_PRETEX)' \
        $(CURDIR)/$<)

heiglogo.sty:
	wget https://github.com/HEIG-VD/logos/releases/download/v0.5.0/heiglogo.sty -O tex/$@

clean:
	latexmk -C
	rm -rf build

revision.tex:
	@printf '%% Autogenerated, do not edit\n' > $@
	@printf '\\newcommand{\\revisiondate}{%s}\n' "`git log -1 --format=\"%ad\" --date=short`" >> $@
	@printf '\\newcommand{\\revision}{%s}\n' "`git describe --always --dirty`" >> $@

.PHONY: clean all
