
TEX_SOURCES := $(sort $(wildcard tex/series/*/*.tex))

PDFS := $(TEX_SOURCES:tex/series/%.tex=build/series/%.pdf)
SOLUTIONS := $(TEX_SOURCES:tex/series/%.tex=build/series/%-solution.pdf)

LATEXMK_FLAGS := -lualatex -interaction=nonstopmode -halt-on-error -silent

all: $(PDFS) $(SOLUTIONS)

build/series/%.pdf: tex/series/%.tex revision.tex heiglogo.sty
	@mkdir -p $(@D)
	latexmk $(LATEXMK_FLAGS) -output-directory=$(@D) $<

build/series/%-solution.pdf: tex/series/%.tex revision.tex heiglogo.sty
	@mkdir -p $(@D)
	latexmk $(LATEXMK_FLAGS) \
		-output-directory=$(@D) \
		-jobname=$(notdir $(basename $(@:.pdf=))) \
		-pdflatex='lualatex %O "\PassOptionsToClass{answers}{exam}\input{%S}"' $<

heiglogo.sty:
	wget https://github.com/HEIG-VD/logos/releases/download/v0.5.0/heiglogo.sty -O tex/series/$@

clean:
	latexmk -C
	rm -rf build

revision.tex:
	@printf '%% Autogenerated, do not edit\n' > $@
	@printf '\\newcommand{\\revisiondate}{%s}\n' "`git log -1 --format=\"%ad\" --date=short`" >> $@
	@printf '\\newcommand{\\revision}{%s}\n' "`git describe --always --dirty`" >> $@

.PHONY: clean all
